@startuml

rectangle Sistema{
(Caso de uso I)
(Caso de uso II)
(Caso de uso III)
}
(Caso de uso I)--:Actor I:
(Caso de uso II)--:Actor I:
(Caso de uso III)--:Actor I:
:Actor II:--(Caso de uso I)
:Actor II:--(Caso de uso III)
@enduml