@startuml
:Agente:->(Evaluar Solicitud de Crédito)
(Evaluar Solicitud de Crédito)<.-(Solicitar información adicional al cliente):<<extend>>
note right on link
Condición:
Si ingresos < 1000
end note
@enduml